changesetIgnorePatterns:
  - "**/*.{test,spec}.{js,jsx,ts,tsx}"

constraintsPath: ./constraints.pro

logFilters:
  - code: YN0062
    level: info

nodeLinker: node-modules

packageExtensions:
  "@apollo/react-hooks@*":
    peerDependencies:
      graphql: "^14.0.0 || ^15.0.0"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: ">=2.7"
  "@graphql-codegen/cli@*":
    peerDependencies:
      typescript: ">=2.7"
  "@graphql-eslint/eslint-plugin@*":
    peerDependencies:
      typescript: ">=2.7"
  "apollo-link-error@*":
    peerDependencies:
      graphql: "^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0"
  "eslint-plugin-editorconfig@*":
    peerDependencies:
      "@typescript-eslint/parser": "^4.0.0"
  "graphql-config@*":
    peerDependencies:
      typescript: ">=2.7"
  "react-dev-utils@*":
    peerDependencies:
      webpack: ">=4"
      typescript: ">=2.7"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferInteractive: true

progressBarStyle: patrick

telemetryUserId: nyoomy

yarnPath: ./.yarn/releases/yarn-berry.cjs
