const path = require('path');

module.exports = [
    {
        name: 'production_connection',
        type: 'postgres',
        host: 'postgres',
        port: 5432,
        username: 'postgres',
        password: 'postgres',
        database: 'nyoomy_db_prod',
        synchronize: true,
        logging: true,
        logNotifications: true,
        dropSchema: true,
        entities: [path.join(__dirname, 'packages/server/src/entity/**/*.ts')],
        migrations: [
            path.join(__dirname, 'packages/server/src/migration/**/*.ts'),
        ],
        subscribers: [
            path.join(__dirname, 'packages/server/src/subscriber/**/*.ts'),
        ],
        cli: {
            entitiesDir: 'packages/server/src/entity',
            migrationsDir: 'packages/server/src/migration',
            subscribersDir: 'packages/server/src/subscriber',
        },
    },
    {
        name: 'development_connection',
        type: 'postgres',
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: 'postgres',
        database: 'nyoomy_db_dev',
        synchronize: true,
        logging: true,
        logNotifications: true,
        dropSchema: true,
        entities: ['packages/server/src/entity/**/*.ts'],
        migrations: ['packages/server/src/migration/**/*.ts'],
        subscribers: ['packages/server/src/subscriber/**/*.ts'],
        cli: {
            entitiesDir: 'packages/server/src/entity',
            migrationsDir: 'packages/server/src/migration',
            subscribersDir: 'packages/server/src/subscriber',
        },
    },
    {
        name: 'default',
        type: 'postgres',
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: 'postgres',
        database: 'nyoomy_db_dev',
        synchronize: true,
        logging: true,
        logNotifications: true,
        dropSchema: true,
        entities: [path.join(__dirname, 'packages/server/src/entity/**/*.ts')],
        migrations: [
            path.join(__dirname, 'packages/server/src/migration/**/*.ts'),
        ],
        subscribers: [
            path.join(__dirname, 'packages/server/src/subscriber/**/*.ts'),
        ],
        cli: {
            entitiesDir: 'packages/server/src/entity',
            migrationsDir: 'packages/server/src/migration',
            subscribersDir: 'packages/server/src/subscriber',
        },
    },
    {
        name: 'test_connection',
        type: 'postgres',
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: 'postgres',
        database: 'nyoomy_db_test',
        synchronize: true,
        logging: true,
        logNotifications: true,
        entities: ['packages/server/src/entity/**/*.ts'],
        migrations: ['packages/server/src/migration/**/*.ts'],
        subscribers: ['packages/server/src/subscriber/**/*.ts'],
        cli: {
            entitiesDir: 'packages/server/src/entity',
            migrationsDir: 'packages/server/src/migration',
            subscribersDir: 'packages/server/src/subscriber',
        },
    },
];
